version: '2.1'

services:
  sgilogging:
    image: sgilogging
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 .